# Generated by Django 4.1.6 on 2023-02-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_author"),
        ("blog", "0010_alter_post_content"),
    ]

    operations = []
